### ISSUE TITLE
CollectionTypeFormComponent disappears

### ISSUE THREAD

**Issue by parijke** [weaverryan/live-demo#11]
When trying the demo, the CollectionTypeFormComponent suddenly disappears. It shows in the debug bar:
The identifier id is missing for a query of App\Entity\Post

Clean build

**Comment by weaverryan** [comment]
Thanks! We're building a new spot for some demos (including better demos). We'll make sure it works there (should be released in the next few weeks). But iirc, this may have been a bug that was fixed in UX 2.1.1, and this demo is still using 2.1.0. So a `composer up` might be enough to get it working again :)

**Comment by parijke** [comment]
Yep, that was it!
