### ISSUE TITLE
Submitting RegistrationForm renders new page

### ISSUE THREAD

**Issue by dbrekelmans** [weaverryan/live-demo#2]
If you submit the registration form and have a form error, it will render a new `/register` page with *only* the registration form on it.

I thought it would have updated the form inside the current page (without rendering a new page). I would think it should be possible an I'm interested to know how to do this. I can't figure it out so far, maybe you can point me in the right direction?

**Comment by weaverryan** [comment]
Hey @dbrekelmans!

Excellent question! The short answer is that you can do it either way. Here are the 2 options:

1) Currently, I render the registration form inside a live component. But I allow the form to submit like normal (no JavaScript or component magic - just a normal form submit). That's why you go to `/register`. This is, "by design" in this case - and I wanted to show how you could use the component to make your form fancy, but still allow it to submit like normal. If your registration form were only ever shown on `/register` then you wouldn't notice.

2) The other option, shown in an example in a different component - https://github.com/weaverryan/live-demo/blob/31fd2708b21cc1dca8a456290a082acf96bc3941/templates/components/edit_post_no_form.html.twig#L55-L59 - is to submit the form through the component via an action. If you do this, then the form submits via Ajax and everything "stays in the component" (and on the same page) like you're expecting. The downside is simply that... if the user doesn't have JavaScript, it won't work. 

Let me know if this clarifies - and thanks for trying things out!

**Comment by dbrekelmans** [comment]
Hey @weaverryan,

I was confused, because I wasn't sure whether it was a bug or a feature ^^
Your response does clarify it, thanks for the explanation.

I will play around with it a bit more this week.
Thanks for the work on the twig- and live-components, I think it will massively improve a lot of people's workflow!
